version: 2

jobs:
  build_and_test:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/CircleCI/docker-airflow
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t duyetdev/airflow .
      - run:
          name: Test Python version
          command: |
            docker run duyetdev/airflow python -V | grep '3.7'
      - run:
          name: Test docker image
          command: |
            docker run duyetdev/airflow version | grep '1.10.5'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
